"""Add project financials

Revision ID: 9f31979ee18a
Revises: 024
Create Date: 2026-02-11 23:26:12.057442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9f31979ee18a'
down_revision: Union[str, None] = '024'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_expenses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('category', sa.Enum('DOMAIN', 'ADS', 'TOOLS', 'HUMAN_RESOURCES', 'OTHER', name='expensecategory', native_enum=False), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('occurred_at', sa.Date(), nullable=False),
    sa.Column('vendor', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projetos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_expenses_category'), 'project_expenses', ['category'], unique=False)
    op.create_index(op.f('ix_project_expenses_id'), 'project_expenses', ['id'], unique=False)
    op.create_index(op.f('ix_project_expenses_occurred_at'), 'project_expenses', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_project_expenses_project_id'), 'project_expenses', ['project_id'], unique=False)
    
    op.add_column('projetos', sa.Column('budget_cents', sa.BigInteger(), nullable=False, server_default='0'))
    op.add_column('projetos', sa.Column('expected_revenue_cents', sa.BigInteger(), nullable=False, server_default='0'))
    op.add_column('projetos', sa.Column('actual_revenue_cents', sa.BigInteger(), nullable=False, server_default='0'))
    
    # Remove server_default after creation if needed, but keeping it is safer for existing rows
    op.alter_column('projetos', 'budget_cents', server_default=None)
    op.alter_column('projetos', 'expected_revenue_cents', server_default=None)
    op.alter_column('projetos', 'actual_revenue_cents', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projetos', 'actual_revenue_cents')
    op.drop_column('projetos', 'expected_revenue_cents')
    op.drop_column('projetos', 'budget_cents')
    op.drop_index(op.f('ix_project_expenses_project_id'), table_name='project_expenses')
    op.drop_index(op.f('ix_project_expenses_occurred_at'), table_name='project_expenses')
    op.drop_index(op.f('ix_project_expenses_id'), table_name='project_expenses')
    op.drop_index(op.f('ix_project_expenses_category'), table_name='project_expenses')
    op.drop_table('project_expenses')
    # ### end Alembic commands ###
