"""Add Multi-Tenant

Revision ID: d1e010ac2e8d
Revises: 9f31979ee18a
Create Date: 2026-04-30 11:59:32.991119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd1e010ac2e8d'
down_revision: Union[str, None] = '9f31979ee18a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome_negocio', sa.String(length=255), nullable=False),
    sa.Column('plano', sa.Enum('basic', 'pro', name='plantype', native_enum=False, length=20), nullable=False),
    sa.Column('llm_model', sa.String(length=100), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('openai_api_key', sa.String(length=255), nullable=True),
    sa.Column('google_calendar_token', sa.Text(), nullable=True),
    sa.Column('evolution_api_url', sa.String(length=500), nullable=True),
    sa.Column('evolution_api_key', sa.String(length=500), nullable=True),
    sa.Column('evolution_instance_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_evolution_instance_name'), 'tenants', ['evolution_instance_name'], unique=False)
    op.create_index(op.f('ix_tenants_id'), 'tenants', ['id'], unique=False)
    op.add_column('agent_conversations', sa.Column('tenant_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_agent_conversations_tenant_id'), 'agent_conversations', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'agent_conversations', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('ai_agents', sa.Column('tenant_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_ai_agents_tenant_id'), 'ai_agents', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'ai_agents', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('campaign_lead_conversations', sa.Column('tenant_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_campaign_lead_conversations_id'), 'campaign_lead_conversations', ['id'], unique=False)
    op.create_index(op.f('ix_campaign_lead_conversations_tenant_id'), 'campaign_lead_conversations', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'campaign_lead_conversations', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('campaign_lead_messages', sa.Column('tenant_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_campaign_lead_messages_id'), 'campaign_lead_messages', ['id'], unique=False)
    op.create_index(op.f('ix_campaign_lead_messages_tenant_id'), 'campaign_lead_messages', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'campaign_lead_messages', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('campaign_leads', sa.Column('tenant_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_campaign_leads_tenant_id'), 'campaign_leads', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'campaign_leads', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('campaigns', sa.Column('tenant_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_campaigns_tenant_id'), 'campaigns', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'campaigns', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('centros_custo', sa.Column('tenant_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_centros_custo_id'), 'centros_custo', ['id'], unique=False)
    op.create_index(op.f('ix_centros_custo_tenant_id'), 'centros_custo', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'centros_custo', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('clientes', sa.Column('tenant_id', sa.UUID(), nullable=True))
    op.alter_column('clientes', 'endereco',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.create_index(op.f('ix_clientes_tenant_id'), 'clientes', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'clientes', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_column('clientes', 'documento')
    op.add_column('contas_bancarias', sa.Column('tenant_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_contas_bancarias_id'), 'contas_bancarias', ['id'], unique=False)
    op.create_index(op.f('ix_contas_bancarias_tenant_id'), 'contas_bancarias', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'contas_bancarias', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('contas_pagar', sa.Column('tenant_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_contas_pagar_id'), 'contas_pagar', ['id'], unique=False)
    op.create_index(op.f('ix_contas_pagar_tenant_id'), 'contas_pagar', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'contas_pagar', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('contas_receber', sa.Column('tenant_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_contas_receber_id'), 'contas_receber', ['id'], unique=False)
    op.create_index(op.f('ix_contas_receber_tenant_id'), 'contas_receber', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'contas_receber', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('contratos', sa.Column('tenant_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_contratos_tenant_id'), 'contratos', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'contratos', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_table_comment(
        'conversation_participants',
        'Participantes de conversas',
        existing_comment=None,
        schema=None
    )
    op.add_column('deal_activities', sa.Column('tenant_id', sa.UUID(), nullable=True))
    op.alter_column('deal_activities', 'type',
               existing_type=postgresql.ENUM('call', 'email', 'meeting', 'whatsapp', 'custom', name='dealactivitytype'),
               type_=sa.Enum('call', 'email', 'meeting', 'whatsapp', 'custom', name='dealactivitytype', native_enum=False, length=20),
               existing_nullable=False)
    op.create_index(op.f('ix_deal_activities_id'), 'deal_activities', ['id'], unique=False)
    op.create_index(op.f('ix_deal_activities_tenant_id'), 'deal_activities', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'deal_activities', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('deal_assignees', sa.Column('tenant_id', sa.UUID(), nullable=True))
    op.drop_constraint('uq_deal_user', 'deal_assignees', type_='unique')
    op.create_index(op.f('ix_deal_assignees_id'), 'deal_assignees', ['id'], unique=False)
    op.create_index(op.f('ix_deal_assignees_tenant_id'), 'deal_assignees', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'deal_assignees', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_table_comment(
        'deal_assignees',
        'Responsáveis atribuídos a deals',
        existing_comment=None,
        schema=None
    )
    op.add_column('deal_notes', sa.Column('tenant_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_deal_notes_id'), 'deal_notes', ['id'], unique=False)
    op.create_index(op.f('ix_deal_notes_tenant_id'), 'deal_notes', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'deal_notes', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('deal_stage_history', sa.Column('tenant_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_deal_stage_history_id'), 'deal_stage_history', ['id'], unique=False)
    op.create_index(op.f('ix_deal_stage_history_tenant_id'), 'deal_stage_history', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'deal_stage_history', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('deal_tag_links', sa.Column('tenant_id', sa.UUID(), nullable=True))
    op.drop_constraint('uq_deal_tag', 'deal_tag_links', type_='unique')
    op.create_index(op.f('ix_deal_tag_links_id'), 'deal_tag_links', ['id'], unique=False)
    op.create_index(op.f('ix_deal_tag_links_tenant_id'), 'deal_tag_links', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'deal_tag_links', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('deal_tags', sa.Column('tenant_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_deal_tags_tenant_id'), 'deal_tags', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'deal_tags', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('deals', sa.Column('tenant_id', sa.UUID(), nullable=True))
    op.alter_column('deals', 'priority',
               existing_type=postgresql.ENUM('low', 'normal', 'high', 'urgent', name='dealpriority'),
               type_=sa.Enum('low', 'normal', 'high', 'urgent', name='dealpriority', native_enum=False, length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'normal'::dealpriority"))
    op.alter_column('deals', 'status',
               existing_type=postgresql.ENUM('open', 'won', 'lost', name='dealstatus'),
               type_=sa.Enum('open', 'won', 'lost', name='dealstatus', native_enum=False, length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'open'::dealstatus"))
    op.alter_column('deals', 'source',
               existing_type=postgresql.ENUM('inbound', 'outbound', 'indicacao', 'evento', 'rede_social', 'outro', name='dealsource'),
               type_=sa.Enum('inbound', 'outbound', 'indicacao', 'evento', 'rede_social', 'outro', name='dealsource', native_enum=False, length=20),
               existing_nullable=True)
    op.create_index(op.f('ix_deals_tenant_id'), 'deals', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'deals', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('despesas_fixas', sa.Column('tenant_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_despesas_fixas_id'), 'despesas_fixas', ['id'], unique=False)
    op.create_index(op.f('ix_despesas_fixas_tenant_id'), 'despesas_fixas', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'despesas_fixas', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('email_outbox', sa.Column('tenant_id', sa.UUID(), nullable=True))
    op.drop_index('ix_email_outbox_status', table_name='email_outbox')
    op.create_index(op.f('ix_email_outbox_id'), 'email_outbox', ['id'], unique=False)
    op.create_index(op.f('ix_email_outbox_tenant_id'), 'email_outbox', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'email_outbox', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_table_comment(
        'email_outbox',
        'Fila de e-mails para envio transacional',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('ix_funcionarios_id'), 'funcionarios', ['id'], unique=False)
    op.add_column('lead_conversations', sa.Column('tenant_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_lead_conversations_tenant_id'), 'lead_conversations', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'lead_conversations', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('lead_messages', sa.Column('tenant_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_lead_messages_tenant_id'), 'lead_messages', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'lead_messages', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('leads', sa.Column('tenant_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_leads_tenant_id'), 'leads', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'leads', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_table_comment(
        'notification_recipients',
        'Inbox por usuário: cada notificação pode ter múltiplos destinatários',
        existing_comment=None,
        schema=None
    )
    op.alter_column('notifications', 'type',
               existing_type=postgresql.ENUM('PROJECT_NUDGE', 'DIRECT_MESSAGE', 'SYSTEM', 'TASK_MENTION', 'PROPOSAL_UPDATE', 'CONTRACT_UPDATE', 'TASK_NUDGE', name='notificationtype'),
               type_=sa.Enum('PROJECT_NUDGE', 'TASK_NUDGE', 'DIRECT_MESSAGE', 'SYSTEM', 'TASK_MENTION', 'PROPOSAL_UPDATE', 'CONTRACT_UPDATE', name='notificationtype', native_enum=False, length=50),
               existing_nullable=False)
    op.alter_column('notifications', 'priority',
               existing_type=postgresql.ENUM('low', 'normal', 'high', 'urgent', name='notificationpriority'),
               type_=sa.Enum('LOW', 'NORMAL', 'HIGH', 'URGENT', name='notificationpriority', native_enum=False, length=20),
               existing_nullable=False)
    op.drop_index('ix_notifications_context', table_name='notifications')
    op.create_index(op.f('ix_notifications_context_id'), 'notifications', ['context_id'], unique=False)
    op.create_index(op.f('ix_notifications_context_type'), 'notifications', ['context_type'], unique=False)
    op.create_index(op.f('ix_permissions_id'), 'permissions', ['id'], unique=False)
    op.add_column('pipeline_stages', sa.Column('tenant_id', sa.UUID(), nullable=True))
    op.drop_constraint('uq_pipeline_stage_order', 'pipeline_stages', type_='unique')
    op.create_index(op.f('ix_pipeline_stages_tenant_id'), 'pipeline_stages', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'pipeline_stages', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_table_comment(
        'pipeline_stages',
        'Etapas do pipeline de vendas',
        existing_comment=None,
        schema=None
    )
    op.add_column('pipelines', sa.Column('tenant_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_pipelines_tenant_id'), 'pipelines', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'pipelines', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_pre_proposal_answer', 'pre_proposal_answers', type_='unique')
    op.create_index(op.f('ix_pre_proposal_answers_id'), 'pre_proposal_answers', ['id'], unique=False)
    op.create_table_comment(
        'pre_proposal_answers',
        'Respostas do diagnóstico de pré-proposta',
        existing_comment=None,
        schema=None
    )
    op.alter_column('pre_proposal_templates', 'is_default',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.create_table_comment(
        'pre_proposal_templates',
        'Templates de diagnóstico para pré-propostas',
        existing_comment=None,
        schema=None
    )
    op.drop_index('ix_pre_proposals_status', table_name='pre_proposals')
    op.add_column('project_expenses', sa.Column('tenant_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_project_expenses_tenant_id'), 'project_expenses', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'project_expenses', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('projetos', sa.Column('tenant_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_projetos_tenant_id'), 'projetos', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'projetos', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_index('ix_proposal_analytics_proposta_date', table_name='proposal_analytics_summary')
    op.drop_index('ix_proposal_events_proposta_type', table_name='proposal_events')
    op.add_column('proposal_pricing_plans', sa.Column('tenant_id', sa.UUID(), nullable=True))
    op.alter_column('proposal_pricing_plans', 'is_recommended',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('proposal_pricing_plans', 'is_selected_default',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.create_index(op.f('ix_proposal_pricing_plans_id'), 'proposal_pricing_plans', ['id'], unique=False)
    op.create_index(op.f('ix_proposal_pricing_plans_tenant_id'), 'proposal_pricing_plans', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'proposal_pricing_plans', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_table_comment(
        'proposal_pricing_plans',
        'Planos de preço da proposta',
        existing_comment=None,
        schema=None
    )
    op.add_column('proposal_sections', sa.Column('tenant_id', sa.UUID(), nullable=True))
    op.drop_constraint('uq_proposal_section_order', 'proposal_sections', type_='unique')
    op.create_index(op.f('ix_proposal_sections_id'), 'proposal_sections', ['id'], unique=False)
    op.create_index(op.f('ix_proposal_sections_tenant_id'), 'proposal_sections', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'proposal_sections', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_table_comment(
        'proposal_sections',
        'Seções editáveis da proposta comercial',
        existing_comment=None,
        schema=None
    )
    op.drop_index('ix_proposal_sessions_proposta_session', table_name='proposal_sessions')
    op.add_column('proposal_status_events', sa.Column('tenant_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_proposal_status_events_id'), 'proposal_status_events', ['id'], unique=False)
    op.create_index(op.f('ix_proposal_status_events_tenant_id'), 'proposal_status_events', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'proposal_status_events', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_table_comment(
        'proposal_status_events',
        'Eventos de tracking da proposta',
        existing_comment=None,
        schema=None
    )
    op.add_column('propostas', sa.Column('tenant_id', sa.UUID(), nullable=True))
    op.alter_column('propostas', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=False,
               existing_server_default=sa.text("'BRL'::character varying"))
    op.drop_constraint('propostas_public_token_key', 'propostas', type_='unique')
    op.create_index(op.f('ix_propostas_tenant_id'), 'propostas', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'propostas', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_index('ix_role_permissions_permission_id', table_name='role_permissions')
    op.drop_index('ix_role_permissions_role_id', table_name='role_permissions')
    op.create_index(op.f('ix_role_permissions_id'), 'role_permissions', ['id'], unique=False)
    op.drop_constraint('roles_key_key', 'roles', type_='unique')
    op.add_column('tarefa_assignees', sa.Column('tenant_id', sa.UUID(), nullable=True))
    op.drop_constraint('uq_tarefa_usuario', 'tarefa_assignees', type_='unique')
    op.create_index(op.f('ix_tarefa_assignees_id'), 'tarefa_assignees', ['id'], unique=False)
    op.create_index(op.f('ix_tarefa_assignees_tenant_id'), 'tarefa_assignees', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'tarefa_assignees', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_table_comment(
        'tarefa_assignees',
        'Permite atribuir múltiplos usuários a uma tarefa',
        existing_comment=None,
        schema=None
    )
    op.add_column('tarefas', sa.Column('tenant_id', sa.UUID(), nullable=True))
    op.alter_column('tarefas', 'projeto_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index('ix_tarefas_context_type_id', table_name='tarefas')
    op.drop_index('ix_tarefas_parent_task_id', table_name='tarefas')
    op.create_index(op.f('ix_tarefas_tenant_id'), 'tarefas', ['tenant_id'], unique=False)
    op.drop_constraint('fk_tarefa_parent_task', 'tarefas', type_='foreignkey')
    op.create_foreign_key(None, 'tarefas', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'tarefas', 'tarefas', ['parent_task_id'], ['id'])
    op.drop_index('ix_task_blocks_order_index', table_name='task_blocks')
    op.create_table_comment(
        'task_blocks',
        'Blocos de conteúdo da tarefa (editor estilo Notion)',
        existing_comment=None,
        schema=None
    )
    op.drop_index('ix_task_databases_is_default', table_name='task_databases')
    op.drop_constraint('uq_task_property_database_key', 'task_properties', type_='unique')
    op.create_table_comment(
        'task_properties',
        'Propriedades customizáveis de tarefas (estilo Notion)',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint('uq_task_property_value', 'task_property_values', type_='unique')
    op.create_table_comment(
        'task_property_values',
        'Valores das propriedades customizáveis por tarefa',
        existing_comment=None,
        schema=None
    )
    op.drop_index('ix_user_roles_role_id', table_name='user_roles')
    op.drop_index('ix_user_roles_user_id', table_name='user_roles')
    op.create_table_comment(
        'user_roles',
        'Multi-cargo: usuários podem ter múltiplos cargos',
        existing_comment=None,
        schema=None
    )
    op.add_column('usuarios', sa.Column('tenant_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_usuarios_tenant_id'), 'usuarios', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'usuarios', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('whatsapp_connections', sa.Column('tenant_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_whatsapp_connections_tenant_id'), 'whatsapp_connections', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'whatsapp_connections', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'whatsapp_connections', type_='foreignkey')
    op.drop_index(op.f('ix_whatsapp_connections_tenant_id'), table_name='whatsapp_connections')
    op.drop_column('whatsapp_connections', 'tenant_id')
    op.drop_constraint(None, 'usuarios', type_='foreignkey')
    op.drop_index(op.f('ix_usuarios_tenant_id'), table_name='usuarios')
    op.drop_column('usuarios', 'tenant_id')
    op.drop_table_comment(
        'user_roles',
        existing_comment='Multi-cargo: usuários podem ter múltiplos cargos',
        schema=None
    )
    op.create_index('ix_user_roles_user_id', 'user_roles', ['user_id'], unique=False)
    op.create_index('ix_user_roles_role_id', 'user_roles', ['role_id'], unique=False)
    op.drop_table_comment(
        'task_property_values',
        existing_comment='Valores das propriedades customizáveis por tarefa',
        schema=None
    )
    op.create_unique_constraint('uq_task_property_value', 'task_property_values', ['task_id', 'property_id'])
    op.drop_table_comment(
        'task_properties',
        existing_comment='Propriedades customizáveis de tarefas (estilo Notion)',
        schema=None
    )
    op.create_unique_constraint('uq_task_property_database_key', 'task_properties', ['task_database_id', 'key'])
    op.create_index('ix_task_databases_is_default', 'task_databases', ['is_default'], unique=False)
    op.drop_table_comment(
        'task_blocks',
        existing_comment='Blocos de conteúdo da tarefa (editor estilo Notion)',
        schema=None
    )
    op.create_index('ix_task_blocks_order_index', 'task_blocks', ['task_id', 'order_index'], unique=False)
    op.drop_constraint(None, 'tarefas', type_='foreignkey')
    op.drop_constraint(None, 'tarefas', type_='foreignkey')
    op.create_foreign_key('fk_tarefa_parent_task', 'tarefas', 'tarefas', ['parent_task_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_tarefas_tenant_id'), table_name='tarefas')
    op.create_index('ix_tarefas_parent_task_id', 'tarefas', ['parent_task_id'], unique=False)
    op.create_index('ix_tarefas_context_type_id', 'tarefas', ['context_type', 'context_id'], unique=False)
    op.alter_column('tarefas', 'projeto_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('tarefas', 'tenant_id')
    op.drop_table_comment(
        'tarefa_assignees',
        existing_comment='Permite atribuir múltiplos usuários a uma tarefa',
        schema=None
    )
    op.drop_constraint(None, 'tarefa_assignees', type_='foreignkey')
    op.drop_index(op.f('ix_tarefa_assignees_tenant_id'), table_name='tarefa_assignees')
    op.drop_index(op.f('ix_tarefa_assignees_id'), table_name='tarefa_assignees')
    op.create_unique_constraint('uq_tarefa_usuario', 'tarefa_assignees', ['tarefa_id', 'usuario_id'])
    op.drop_column('tarefa_assignees', 'tenant_id')
    op.create_unique_constraint('roles_key_key', 'roles', ['key'])
    op.drop_index(op.f('ix_role_permissions_id'), table_name='role_permissions')
    op.create_index('ix_role_permissions_role_id', 'role_permissions', ['role_id'], unique=False)
    op.create_index('ix_role_permissions_permission_id', 'role_permissions', ['permission_id'], unique=False)
    op.drop_constraint(None, 'propostas', type_='foreignkey')
    op.drop_index(op.f('ix_propostas_tenant_id'), table_name='propostas')
    op.create_unique_constraint('propostas_public_token_key', 'propostas', ['public_token'])
    op.alter_column('propostas', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=True,
               existing_server_default=sa.text("'BRL'::character varying"))
    op.drop_column('propostas', 'tenant_id')
    op.drop_table_comment(
        'proposal_status_events',
        existing_comment='Eventos de tracking da proposta',
        schema=None
    )
    op.drop_constraint(None, 'proposal_status_events', type_='foreignkey')
    op.drop_index(op.f('ix_proposal_status_events_tenant_id'), table_name='proposal_status_events')
    op.drop_index(op.f('ix_proposal_status_events_id'), table_name='proposal_status_events')
    op.drop_column('proposal_status_events', 'tenant_id')
    op.create_index('ix_proposal_sessions_proposta_session', 'proposal_sessions', ['proposta_id', 'session_id'], unique=False)
    op.drop_table_comment(
        'proposal_sections',
        existing_comment='Seções editáveis da proposta comercial',
        schema=None
    )
    op.drop_constraint(None, 'proposal_sections', type_='foreignkey')
    op.drop_index(op.f('ix_proposal_sections_tenant_id'), table_name='proposal_sections')
    op.drop_index(op.f('ix_proposal_sections_id'), table_name='proposal_sections')
    op.create_unique_constraint('uq_proposal_section_order', 'proposal_sections', ['proposal_id', 'order_index'])
    op.drop_column('proposal_sections', 'tenant_id')
    op.drop_table_comment(
        'proposal_pricing_plans',
        existing_comment='Planos de preço da proposta',
        schema=None
    )
    op.drop_constraint(None, 'proposal_pricing_plans', type_='foreignkey')
    op.drop_index(op.f('ix_proposal_pricing_plans_tenant_id'), table_name='proposal_pricing_plans')
    op.drop_index(op.f('ix_proposal_pricing_plans_id'), table_name='proposal_pricing_plans')
    op.alter_column('proposal_pricing_plans', 'is_selected_default',
               existing_type=sa.String(length=20),
               type_=sa.BOOLEAN(),
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('proposal_pricing_plans', 'is_recommended',
               existing_type=sa.String(length=20),
               type_=sa.BOOLEAN(),
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_column('proposal_pricing_plans', 'tenant_id')
    op.create_index('ix_proposal_events_proposta_type', 'proposal_events', ['proposta_id', 'event_type'], unique=False)
    op.create_index('ix_proposal_analytics_proposta_date', 'proposal_analytics_summary', ['proposta_id', 'date'], unique=False)
    op.drop_constraint(None, 'projetos', type_='foreignkey')
    op.drop_index(op.f('ix_projetos_tenant_id'), table_name='projetos')
    op.drop_column('projetos', 'tenant_id')
    op.drop_constraint(None, 'project_expenses', type_='foreignkey')
    op.drop_index(op.f('ix_project_expenses_tenant_id'), table_name='project_expenses')
    op.drop_column('project_expenses', 'tenant_id')
    op.create_index('ix_pre_proposals_status', 'pre_proposals', ['status'], unique=False)
    op.drop_table_comment(
        'pre_proposal_templates',
        existing_comment='Templates de diagnóstico para pré-propostas',
        schema=None
    )
    op.alter_column('pre_proposal_templates', 'is_default',
               existing_type=sa.String(length=20),
               type_=sa.BOOLEAN(),
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_table_comment(
        'pre_proposal_answers',
        existing_comment='Respostas do diagnóstico de pré-proposta',
        schema=None
    )
    op.drop_index(op.f('ix_pre_proposal_answers_id'), table_name='pre_proposal_answers')
    op.create_unique_constraint('uq_pre_proposal_answer', 'pre_proposal_answers', ['pre_proposal_id', 'field_key'])
    op.drop_constraint(None, 'pipelines', type_='foreignkey')
    op.drop_index(op.f('ix_pipelines_tenant_id'), table_name='pipelines')
    op.drop_column('pipelines', 'tenant_id')
    op.drop_table_comment(
        'pipeline_stages',
        existing_comment='Etapas do pipeline de vendas',
        schema=None
    )
    op.drop_constraint(None, 'pipeline_stages', type_='foreignkey')
    op.drop_index(op.f('ix_pipeline_stages_tenant_id'), table_name='pipeline_stages')
    op.create_unique_constraint('uq_pipeline_stage_order', 'pipeline_stages', ['pipeline_id', 'order_index'])
    op.drop_column('pipeline_stages', 'tenant_id')
    op.drop_index(op.f('ix_permissions_id'), table_name='permissions')
    op.drop_index(op.f('ix_notifications_context_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_context_id'), table_name='notifications')
    op.create_index('ix_notifications_context', 'notifications', ['context_type', 'context_id'], unique=False)
    op.alter_column('notifications', 'priority',
               existing_type=sa.Enum('LOW', 'NORMAL', 'HIGH', 'URGENT', name='notificationpriority', native_enum=False, length=20),
               type_=postgresql.ENUM('low', 'normal', 'high', 'urgent', name='notificationpriority'),
               existing_nullable=False)
    op.alter_column('notifications', 'type',
               existing_type=sa.Enum('PROJECT_NUDGE', 'TASK_NUDGE', 'DIRECT_MESSAGE', 'SYSTEM', 'TASK_MENTION', 'PROPOSAL_UPDATE', 'CONTRACT_UPDATE', name='notificationtype', native_enum=False, length=50),
               type_=postgresql.ENUM('PROJECT_NUDGE', 'DIRECT_MESSAGE', 'SYSTEM', 'TASK_MENTION', 'PROPOSAL_UPDATE', 'CONTRACT_UPDATE', 'TASK_NUDGE', name='notificationtype'),
               existing_nullable=False)
    op.drop_table_comment(
        'notification_recipients',
        existing_comment='Inbox por usuário: cada notificação pode ter múltiplos destinatários',
        schema=None
    )
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.drop_index(op.f('ix_leads_tenant_id'), table_name='leads')
    op.drop_column('leads', 'tenant_id')
    op.drop_constraint(None, 'lead_messages', type_='foreignkey')
    op.drop_index(op.f('ix_lead_messages_tenant_id'), table_name='lead_messages')
    op.drop_column('lead_messages', 'tenant_id')
    op.drop_constraint(None, 'lead_conversations', type_='foreignkey')
    op.drop_index(op.f('ix_lead_conversations_tenant_id'), table_name='lead_conversations')
    op.drop_column('lead_conversations', 'tenant_id')
    op.drop_index(op.f('ix_funcionarios_id'), table_name='funcionarios')
    op.drop_table_comment(
        'email_outbox',
        existing_comment='Fila de e-mails para envio transacional',
        schema=None
    )
    op.drop_constraint(None, 'email_outbox', type_='foreignkey')
    op.drop_index(op.f('ix_email_outbox_tenant_id'), table_name='email_outbox')
    op.drop_index(op.f('ix_email_outbox_id'), table_name='email_outbox')
    op.create_index('ix_email_outbox_status', 'email_outbox', ['status'], unique=False)
    op.drop_column('email_outbox', 'tenant_id')
    op.drop_constraint(None, 'despesas_fixas', type_='foreignkey')
    op.drop_index(op.f('ix_despesas_fixas_tenant_id'), table_name='despesas_fixas')
    op.drop_index(op.f('ix_despesas_fixas_id'), table_name='despesas_fixas')
    op.drop_column('despesas_fixas', 'tenant_id')
    op.drop_constraint(None, 'deals', type_='foreignkey')
    op.drop_index(op.f('ix_deals_tenant_id'), table_name='deals')
    op.alter_column('deals', 'source',
               existing_type=sa.Enum('inbound', 'outbound', 'indicacao', 'evento', 'rede_social', 'outro', name='dealsource', native_enum=False, length=20),
               type_=postgresql.ENUM('inbound', 'outbound', 'indicacao', 'evento', 'rede_social', 'outro', name='dealsource'),
               existing_nullable=True)
    op.alter_column('deals', 'status',
               existing_type=sa.Enum('open', 'won', 'lost', name='dealstatus', native_enum=False, length=20),
               type_=postgresql.ENUM('open', 'won', 'lost', name='dealstatus'),
               existing_nullable=False,
               existing_server_default=sa.text("'open'::dealstatus"))
    op.alter_column('deals', 'priority',
               existing_type=sa.Enum('low', 'normal', 'high', 'urgent', name='dealpriority', native_enum=False, length=20),
               type_=postgresql.ENUM('low', 'normal', 'high', 'urgent', name='dealpriority'),
               existing_nullable=False,
               existing_server_default=sa.text("'normal'::dealpriority"))
    op.drop_column('deals', 'tenant_id')
    op.drop_constraint(None, 'deal_tags', type_='foreignkey')
    op.drop_index(op.f('ix_deal_tags_tenant_id'), table_name='deal_tags')
    op.drop_column('deal_tags', 'tenant_id')
    op.drop_constraint(None, 'deal_tag_links', type_='foreignkey')
    op.drop_index(op.f('ix_deal_tag_links_tenant_id'), table_name='deal_tag_links')
    op.drop_index(op.f('ix_deal_tag_links_id'), table_name='deal_tag_links')
    op.create_unique_constraint('uq_deal_tag', 'deal_tag_links', ['deal_id', 'tag_id'])
    op.drop_column('deal_tag_links', 'tenant_id')
    op.drop_constraint(None, 'deal_stage_history', type_='foreignkey')
    op.drop_index(op.f('ix_deal_stage_history_tenant_id'), table_name='deal_stage_history')
    op.drop_index(op.f('ix_deal_stage_history_id'), table_name='deal_stage_history')
    op.drop_column('deal_stage_history', 'tenant_id')
    op.drop_constraint(None, 'deal_notes', type_='foreignkey')
    op.drop_index(op.f('ix_deal_notes_tenant_id'), table_name='deal_notes')
    op.drop_index(op.f('ix_deal_notes_id'), table_name='deal_notes')
    op.drop_column('deal_notes', 'tenant_id')
    op.drop_table_comment(
        'deal_assignees',
        existing_comment='Responsáveis atribuídos a deals',
        schema=None
    )
    op.drop_constraint(None, 'deal_assignees', type_='foreignkey')
    op.drop_index(op.f('ix_deal_assignees_tenant_id'), table_name='deal_assignees')
    op.drop_index(op.f('ix_deal_assignees_id'), table_name='deal_assignees')
    op.create_unique_constraint('uq_deal_user', 'deal_assignees', ['deal_id', 'user_id'])
    op.drop_column('deal_assignees', 'tenant_id')
    op.drop_constraint(None, 'deal_activities', type_='foreignkey')
    op.drop_index(op.f('ix_deal_activities_tenant_id'), table_name='deal_activities')
    op.drop_index(op.f('ix_deal_activities_id'), table_name='deal_activities')
    op.alter_column('deal_activities', 'type',
               existing_type=sa.Enum('call', 'email', 'meeting', 'whatsapp', 'custom', name='dealactivitytype', native_enum=False, length=20),
               type_=postgresql.ENUM('call', 'email', 'meeting', 'whatsapp', 'custom', name='dealactivitytype'),
               existing_nullable=False)
    op.drop_column('deal_activities', 'tenant_id')
    op.drop_table_comment(
        'conversation_participants',
        existing_comment='Participantes de conversas',
        schema=None
    )
    op.drop_constraint(None, 'contratos', type_='foreignkey')
    op.drop_index(op.f('ix_contratos_tenant_id'), table_name='contratos')
    op.drop_column('contratos', 'tenant_id')
    op.drop_constraint(None, 'contas_receber', type_='foreignkey')
    op.drop_index(op.f('ix_contas_receber_tenant_id'), table_name='contas_receber')
    op.drop_index(op.f('ix_contas_receber_id'), table_name='contas_receber')
    op.drop_column('contas_receber', 'tenant_id')
    op.drop_constraint(None, 'contas_pagar', type_='foreignkey')
    op.drop_index(op.f('ix_contas_pagar_tenant_id'), table_name='contas_pagar')
    op.drop_index(op.f('ix_contas_pagar_id'), table_name='contas_pagar')
    op.drop_column('contas_pagar', 'tenant_id')
    op.drop_constraint(None, 'contas_bancarias', type_='foreignkey')
    op.drop_index(op.f('ix_contas_bancarias_tenant_id'), table_name='contas_bancarias')
    op.drop_index(op.f('ix_contas_bancarias_id'), table_name='contas_bancarias')
    op.drop_column('contas_bancarias', 'tenant_id')
    op.add_column('clientes', sa.Column('documento', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'clientes', type_='foreignkey')
    op.drop_index(op.f('ix_clientes_tenant_id'), table_name='clientes')
    op.alter_column('clientes', 'endereco',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('clientes', 'tenant_id')
    op.drop_constraint(None, 'centros_custo', type_='foreignkey')
    op.drop_index(op.f('ix_centros_custo_tenant_id'), table_name='centros_custo')
    op.drop_index(op.f('ix_centros_custo_id'), table_name='centros_custo')
    op.drop_column('centros_custo', 'tenant_id')
    op.drop_constraint(None, 'campaigns', type_='foreignkey')
    op.drop_index(op.f('ix_campaigns_tenant_id'), table_name='campaigns')
    op.drop_column('campaigns', 'tenant_id')
    op.drop_constraint(None, 'campaign_leads', type_='foreignkey')
    op.drop_index(op.f('ix_campaign_leads_tenant_id'), table_name='campaign_leads')
    op.drop_column('campaign_leads', 'tenant_id')
    op.drop_constraint(None, 'campaign_lead_messages', type_='foreignkey')
    op.drop_index(op.f('ix_campaign_lead_messages_tenant_id'), table_name='campaign_lead_messages')
    op.drop_index(op.f('ix_campaign_lead_messages_id'), table_name='campaign_lead_messages')
    op.drop_column('campaign_lead_messages', 'tenant_id')
    op.drop_constraint(None, 'campaign_lead_conversations', type_='foreignkey')
    op.drop_index(op.f('ix_campaign_lead_conversations_tenant_id'), table_name='campaign_lead_conversations')
    op.drop_index(op.f('ix_campaign_lead_conversations_id'), table_name='campaign_lead_conversations')
    op.drop_column('campaign_lead_conversations', 'tenant_id')
    op.drop_constraint(None, 'ai_agents', type_='foreignkey')
    op.drop_index(op.f('ix_ai_agents_tenant_id'), table_name='ai_agents')
    op.drop_column('ai_agents', 'tenant_id')
    op.drop_constraint(None, 'agent_conversations', type_='foreignkey')
    op.drop_index(op.f('ix_agent_conversations_tenant_id'), table_name='agent_conversations')
    op.drop_column('agent_conversations', 'tenant_id')
    op.drop_index(op.f('ix_tenants_id'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_evolution_instance_name'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
