"""Add AgentLog table

Revision ID: ec6938eedad0
Revises: fa19ab368ad0
Create Date: 2026-05-08 20:25:37.258961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec6938eedad0'
down_revision: Union[str, None] = 'fa19ab368ad0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_logs',
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('lead_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['ai_agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_logs_agent_id'), 'agent_logs', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_logs_id'), 'agent_logs', ['id'], unique=False)
    op.create_index(op.f('ix_agent_logs_lead_id'), 'agent_logs', ['lead_id'], unique=False)
    op.create_index(op.f('ix_agent_logs_tenant_id'), 'agent_logs', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_logs_tenant_id'), table_name='agent_logs')
    op.drop_index(op.f('ix_agent_logs_lead_id'), table_name='agent_logs')
    op.drop_index(op.f('ix_agent_logs_id'), table_name='agent_logs')
    op.drop_index(op.f('ix_agent_logs_agent_id'), table_name='agent_logs')
    op.drop_table('agent_logs')
    # ### end Alembic commands ###
