"""Add Sofia Agent tables

Revision ID: fa19ab368ad0
Revises: 026_tenant_site
Create Date: 2026-05-08 19:59:50.783564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa19ab368ad0'
down_revision: Union[str, None] = '026_tenant_site'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_productivity_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('month_year', sa.String(length=7), nullable=False),
    sa.Column('productivity_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('tasks_completed_on_time', sa.Integer(), nullable=True),
    sa.Column('tasks_completed_late', sa.Integer(), nullable=True),
    sa.Column('tasks_pending', sa.Integer(), nullable=True),
    sa.Column('tasks_overdue', sa.Integer(), nullable=True),
    sa.Column('last_calculated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'month_year', name='uq_user_month_productivity'),
    comment='Métricas de produtividade mensal por usuário'
    )
    op.create_index(op.f('ix_user_productivity_metrics_id'), 'user_productivity_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_user_productivity_metrics_user_id'), 'user_productivity_metrics', ['user_id'], unique=False)
    op.create_table('lead_appointments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('google_event_id', sa.String(length=255), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('summary', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_appointments_id'), 'lead_appointments', ['id'], unique=False)
    op.create_index(op.f('ix_lead_appointments_lead_id'), 'lead_appointments', ['lead_id'], unique=False)
    op.create_table('lead_followups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_followups_id'), 'lead_followups', ['id'], unique=False)
    op.create_index(op.f('ix_lead_followups_lead_id'), 'lead_followups', ['lead_id'], unique=False)
    op.create_index(op.f('ix_lead_followups_tenant_id'), 'lead_followups', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lead_followups_tenant_id'), table_name='lead_followups')
    op.drop_index(op.f('ix_lead_followups_lead_id'), table_name='lead_followups')
    op.drop_index(op.f('ix_lead_followups_id'), table_name='lead_followups')
    op.drop_table('lead_followups')
    op.drop_index(op.f('ix_lead_appointments_lead_id'), table_name='lead_appointments')
    op.drop_index(op.f('ix_lead_appointments_id'), table_name='lead_appointments')
    op.drop_table('lead_appointments')
    op.drop_index(op.f('ix_user_productivity_metrics_user_id'), table_name='user_productivity_metrics')
    op.drop_index(op.f('ix_user_productivity_metrics_id'), table_name='user_productivity_metrics')
    op.drop_table('user_productivity_metrics')
    # ### end Alembic commands ###
